export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_COMMENTS = "FETCH_COMMENTS";

export const FETCH_POST = "FETCH_POST";
export const UPDATE_POST = "UPDATE_POST";
export const CREATE_POST = "CREATE_POST";
export const SAVE_POST = "SAVE_POST";
export const DELETE_POST = "DELETE_POST";

export const FETCH_COMMENT = "FETCH_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const SAVE_COMMENT = "SAVE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const VOTE_COMMENT = "VOTE_COMMENT";
