// categories
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";

// orderKey
export const UPDATE_POST_ORDER_KEY = "UPDATE_POST_ORDER_KEY";
export const UPDATE_COMMENT_ORDER_KEY = "UPDATE_COMMENT_ORDER_KEY";

// posts
export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_POST = "FETCH_POST";
export const CREATE_POST = "CREATE_POST";
export const EDIT_POST = "EDIT_POST";
export const VOTE_POST = "VOTE_POST";
export const DELETE_POST = "DELETE_POST";
// postForm
export const UPDATE_POST_FORM = "UPDATE_POST_FORM";

// comments
export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const EDIT_COMMENT = "EDIT_COMMENT";
export const VOTE_COMMENT = "VOTE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
// commentForm
export const UPDATE_COMMENT_FORM = "UPDATE_COMMENT_FORM";
export const RESET_COMMENT_FORM = "RESET_COMMENT_FORM";
export const UPDATE_COMMENT_EDIT_FORM = "UPDATE_COMMENT_EDIT_FORM";
export const RESET_COMMENT_EDIT_FORM = "RESET_COMMENT_EDIT_FORM";
